FROM openjdk:8-jdk-alpine
MAINTAINER emmanuelthecoolest@rocketmail.com
COPY target/spring-injectprops.jar /opt/spring/spring-injectingprops.jar
CMD ["java", "-jar", "/opt/spring/spring-injectingprops.jar"]
EXPOSE 9000
